// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: greet/v1/greet.proto
//
package greet.v1

import com.connectrpc.Headers
import com.connectrpc.MethodSpec
import com.connectrpc.ProtocolClientInterface
import com.connectrpc.ResponseMessage
import com.connectrpc.StreamType

public class GreetServiceClient(
  private val client: ProtocolClientInterface,
) : GreetServiceClientInterface {
  override suspend fun greet(request: Greet.GreetRequest, headers: Headers):
      ResponseMessage<Greet.GreetResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "greet.v1.GreetService/Greet",
      greet.v1.Greet.GreetRequest::class,
      greet.v1.Greet.GreetResponse::class,
      StreamType.UNARY,
    ),
  )

}
