// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: greet/v1/greet.proto
//
package greet.v1

import com.connectrpc.Headers
import com.connectrpc.ResponseMessage

public interface GreetServiceClientInterface {
  public suspend fun greet(request: Greet.GreetRequest, headers: Headers = emptyMap()):
      ResponseMessage<Greet.GreetResponse>
}
